"""add_company_settings

Revision ID: ba6e2dc4f065
Revises: 2f907c8f8ab3
Create Date: 2026-04-10 22:47:59.836456

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ba6e2dc4f065'
down_revision: Union[str, None] = '2f907c8f8ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('invoice_prefix', sa.String(length=20), nullable=True),
    sa.Column('invoice_next_number', sa.Integer(), nullable=True),
    sa.Column('tva_rate', sa.String(length=10), nullable=True),
    sa.Column('invoice_footer', sa.Text(), nullable=True),
    sa.Column('enabled_payments', sa.Text(), nullable=True),
    sa.Column('enabled_alerts', sa.Text(), nullable=True),
    sa.Column('alert_days_before', sa.Integer(), nullable=True),
    sa.Column('hide_ca', sa.Boolean(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('date_format', sa.String(length=20), nullable=True),
    sa.Column('week_start', sa.String(length=10), nullable=True),
    sa.Column('notif_new_ride', sa.Boolean(), nullable=True),
    sa.Column('notif_unpaid', sa.Boolean(), nullable=True),
    sa.Column('notif_alerts', sa.Boolean(), nullable=True),
    sa.Column('notif_daily_report', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_settings')
    # ### end Alembic commands ###
